version: "3"
services:
    web:
        image: node
        restart: always
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: nodejs
        environment:
            NODE_ENV: production
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        # depends_on:
        #  - nginx
        # - /app/node_modules
        # env_file:
        #   - ./envFiles/.env
        links:
            - "redis"
    redis:
        image: "redis:alpine"

    nginx:
        image: nginx
        # build:
        #   context: .
        #   dockerfile: ./docker/NginxDockerfile
        ports:
            - "80:80"
        volumes:
            - ./proxy:/etc/nginx/conf.d
        depends_on:
            - web
    # mongo:
    #   image: "mongo"
    #   restart: always
    #   ports:
    #    - "27017:27017"
    #   volumes:
    #     - ./data:/data/db
volumes:
    data:
